### ISSUE TITLE
[SEC] Is possible to catch users information without log in (submissoes domain)

### ISSUE THREAD

**Issue by carloseduleal** [agile-alliance-brazil/event_registrations#102]
How to reproduce that?
Just access this link without authentication: https://submissoes-staging.agilebrazil.com/users/6

Main trouble:
The user account is being displayed (thiagovilaca according the example). It can help malicious persons to try a brute force attack.

**Comment by celsoMartins** [comment]
Thanks!

Seems like a submission system issue.

@hugocorbucci can you please confirm this?

**Comment by celsoMartins** [comment]
Folks, I will close this issue, since is a submissoes problem and we can't deal with it here. Thanks for the feedback..

**Comment by hugocorbucci** [comment]
I just wanted to point out that hiding user id is not a solution to avoid brute force attacks.
Exponential back off of sign in attempts is a lot more powerful to stop brute force attacks than trying to hide a user's id.
Everyone knows everyone's twitter id and the majority of IDs people chose are easily guessable. The password is the part that is to be kept hidden and brute force attempts against that password is prevented by making every failed attempt take longer.
