### ISSUE TITLE
After PagSeguro confirm the payment the user is redirected to AB Registration and still see the payment options

### ISSUE THREAD

**Issue by rcursino** [agile-alliance-brazil/event_registrations#117]
Steps to reproduce the issue:
1. Create a New Registration
2. Fill in all the required fields
3. Submit registration
4. Click on Pagar PagSeguro image to proceed with the payment and complete the registration process
5. Enter the information on PagSeguro page and pay the amount
6. On the payment confirmation page on PagSeguro, after some time the user will be redirected to Agile Brazil page
7. Observe the page that is launched

Actual Results:
7. The user is redirected to the Registration details page and the Instructions to complete the registration process and the payment options are still displayed.

Expected Results: 
7. Since the payment was already done and confirmed by PagSeguro, the AB Registration page should not display the payment options anymore.

![screen shot 2015-05-02 at 11 03 55 pm](https://cloud.githubusercontent.com/assets/2363171/7443450/0378c7dc-f121-11e4-9222-c1d393cc73d9.png)

**Comment by celsoMartins** [comment]
https://github.com/agile-alliance-brazil/event_registrations/pull/122
