### ISSUE TITLE
Update the URL displayed at the Important section of Registration details page

### ISSUE THREAD

**Issue by rcursino** [agile-alliance-brazil/event_registrations#118]
Steps to reproduce the issue:
Create a New Registration and observe the information Important section of Registration details page

Actual Results:
The URL http://localhost:9292/link is displayed.

Expected Results: 
Update the URL to launch the correct page.

![screen shot 2015-05-02 at 11 25 29 pm](https://cloud.githubusercontent.com/assets/2363171/7443482/8dbf0a62-f123-11e4-813d-4a396affe92c.png)

**Comment by celsoMartins** [comment]
This will be updated when we have the link to table in the site.
