### ISSUE TITLE
All the registration values are zero for a group

### ISSUE THREAD

**Issue by rcursino** [agile-alliance-brazil/event_registrations#120]
Setup:
There is a group with some attendances(more than minimum size for the group).

Steps to reproduce the issue:
1. Login using ADMIN (and Leader group) account 
2. Go to list groups, select the group mentioned above and click on the name link.
3. Verify the values on 'Details for group' page.
4. Pay all registrations for this group

Actual Results:
3. All the registration values are correct according to the group discount and the number of the attendances. 
4. The leader can make the paymentof the group

Expected Results: 
3. All the registration values are zero.
4. It's not possible to pay the registrations of the group (only the 'Check as paid' button is available).
![details_group](https://cloud.githubusercontent.com/assets/2363171/7443502/e4ae1d0c-f125-11e4-8676-53f02f76a5e2.png)

**Comment by celsoMartins** [comment]
Yes. I was investigating this early morning, when I need to out. William assumed this and we will check if everything is ok. This issues happens only in staging. =(

This is the highest priority.

**Comment by celsoMartins** [comment]
The mysql database on staging is not considering decimals. So we change the price to 2.00 and the value is shown again.
