### ISSUE TITLE
Group payment

### ISSUE THREAD

**Issue by celsoMartins** [agile-alliance-brazil/event_registrations#206]
Pessoal, gostaria de debater idéias sobre os grupos no sistema.

Hoje temos grupos resolvendo todas as nossas excessões no sistema. Mas como toda decisão, ela vem acompanhada de pontos positivos e negativos (ou problemas).

Acho que o ponto positivo principal, que na verdade serviu como pilar dessa decisão, foi a simplificação. 3 campos de configuração do grupo, um token e o céu é o limite.

É para deixarmos o participante realizar o pagamento individual? Podemos facilmente usar o status "confirmado" para lidar com isso, o que implica em outra situação: o que fazer com o prazo de pagamento? Em um grupo de 5, 2 pagam e 3 deixam a inscrição vencer. Vamos devolver o dinheiro dos 2 que pagaram? Integral?

Hoje o participante pode realizar o pagamento individual mesmo estando em um grupo. Deixei assim por conta de grupos, como os membros da AA e estudantes, onde o pagamento integral não faz o menor sentido.

Escrevendo aqui, pensei em uma solução que talvez nos permita lidar com essa diferença. Estes grupos especiais não possuem uma quantidade mínima de membros e posso usar essa informação para decidir se mostro o botão de pagamento ou não. Caso nossa decisão seja por não permitir pagamento individual em grupos.

O que acham?

**Comment by LuMoraes** [comment]
Acho que a possibilidade de pagar individualmente a inscrição dentro de um grupo pode ajudar a aumentar o número de pessoas que montam grupos. Podemos incentivar caravanas etc.

No entanto, é realmente difícil lidar com essa questão do pagamento, pois pode ser que nem todos paguem e o grupo fique "incompleto". Acho que é até por isso que geralmente pedimos o pagamento integral do grupo.

Devolver o dinheiro se o grupo não se completar acaba gerando custos para o evento de alguma forma. Deixar a pessoa participar com um desconto que ela não deveria ter porque o grupo não se completou também não é justo.

**Comment by vieiragabriel** [comment]
Acho que poderia devolver 85% do dinheiro pago. Tem que analisar custos e tempo empregado para ter certeza sobre este percentual, é claro!
Penso que assim se coloca mais uma seriedade entre os membros do grupo, um pressiona o outro já que estamos falando do bolso.

**Comment by celsoMartins** [comment]
Eu concordo com a Lu e com a solução do Gabriel. Podemos incluir a política no cancelamento individual na política de cancelamento de grupos, caso alguém tenha pago e o grupo não ter se completado.

**Comment by vieiragabriel** [comment]
Celso,

Quão complexo e/ou demorado é isto?

Abs,

Gabriel Vieira

**Comment by celsoMartins** [comment]
A implementação já está pronta. As pessoas de um grupo só são confirmadas se o grupo estiver completo. Completo = (número de pagos == quantidade mínima).

Dependendo da decisão aqui, a única implementação necessária no sistema de inscrições seria a retirada ou não do botão de pagamento, quando a inscrição for em grupo. Para isso, está ridiculamente fácil de implementar:

**Opção A**: Preciso mudar, mas é uma task de 15 minutos incluindo o deploy e testes.
- Inscrição em grupo e o grupo ainda não está completo: Esconde o botão de pagamento individual.
- Inscrição em grupo e o grupo está completo: Mostra o botão de pagamento individual.

**Opção B**: Atualmente está assim e as mudanças seriam na definição das regras e na exibição claríssima dessa regra no site.
- Inscrição em grupo e o grupo ainda não está completo: Mostra o botão de pagamento individual. Se o grupo não for completado, a devolução ocorrerá de acordo com as regras gerais de devolução.

**Comment by celsoMartins** [comment]
Está mais fácil de implementar que de explicar. kkkkk

**Comment by vieiragabriel** [comment]
Para mim ficou super claro! hahahah

Eu iria de opção B

Abs,

Gabriel Vieira

**Comment by celsoMartins** [comment]
Então fechou opção B?

**Comment by hugocorbucci** [comment]
Eu entendo a opção B como mais simples. No entendo, lidar com a devolução é um saco.
Na linha de forçar, eu sugiro até uma opção C que é uma versão da B.

Pagamento individual é possível.
As inscrições não são confirmadas até o número mínimo de pessoas no grupo completar o pagamento.
Se os participantes quiserem 'desistir' do grupo, eles devem manualmente pedir o cancelamento da inscrição e seguem a política normal de cancelamento (como indivíduos).

Faz sentido?

**Comment by celsoMartins** [comment]
Não sei se entendi bem, Hugo.

É exatamente isso que penso como a opção B. Se 4 pessoas se inscreveram e o grupo não se completou, vamos tratar individualmente essas devoluções.

Talvez, pelo fato de estarmos a 30 dias do evento e já estarmos lidando bem com isso, talvez seja uma issue inter-temporada do AB.

**Comment by hugocorbucci** [comment]
Ah...
Eu tinha entendido que o cancelamento seria do grupo na opção e
aplicaríamos esses 85% (ou seja lá o que for) para todos... eu estava
falando que o problema é dos membros do grupo.
Se 1 deles pedir cancelamento 6 meses antes, ele recebe o que for
estabelecido para isso.
Se 1 deles não pedir o cancelamento, a inscrição fica pendente e, no dia do
evento, se a pessoa quiser confirmar a inscrição, ela paga a diferença  ou
segue o cancelamento como seria normalmente (sem reembolso).

Abs

Hugo Corbucci
Skype user: hugo.corbucci
Twitter: hugocorbucci

2015-09-23 7:35 GMT-07:00 Celso Martins <notifications@github.com>:

**Comment by celsoMartins** [comment]
touché

**Comment by vieiragabriel** [comment]
Escreveu tudo... Agora é só programar! Kkkk

On Wednesday, 23 September 2015, Celso Martins <notifications@github.com>
wrote:

> touché
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agile-alliance-brazil/event_registrations/issues/206#issuecomment-142669533>
> .
>


-- 
Att,

Gabriel Vieira

**Comment by celsoMartins** [comment]
Rapaz.. acho que não precisa desenvolver nada para essa opção não.

Nesse fim de semana vou dar uma olhada.

**Comment by celsoMartins** [comment]
Vou abrir uma discussão por email.
