### ISSUE TITLE
Event organizer should be able to mark an attendance with 'no show'

### ISSUE THREAD

**Issue by celsoMartins** [agile-alliance-brazil/event_registrations#231]

**Comment by hugocorbucci** [comment]
I am torn whether or not this should be in the registrations system.
My dream is that we would have a checking-in or live event or something along those lines for the 3 days of the event. That system would be better off having this information.

But I realize we're far from that.

**Comment by celsoMartins** [comment]
Just a little bit. =)

**Comment by celsoMartins** [comment]
We are going with a **manual** rake task as follow:

```rake registration:no_show```

Maybe you will need to prepend the command with bundle exec

```bundle exec rake registration:no_show```

As a complement to this task, I've changed the logic for active attendances, excluding no_show attendances on the ```active``` scope.

**Comment by celsoMartins** [comment]
19 foram marcados como no_show

![image](https://cloud.githubusercontent.com/assets/214322/11228520/36efc986-8d74-11e5-820e-91012393f24d.png)
