### ISSUE TITLE
No edit option for groups

### ISSUE THREAD

**Issue by vieiragabriel** [agile-alliance-brazil/event_registrations#288]
I have no edit option for groups.
![screen shot 2016-02-22 at 08 59 04](https://cloud.githubusercontent.com/assets/4423187/13217650/ccee3de0-d942-11e5-84c4-3bedb4723c39.png)

**Comment by vieiragabriel** [comment]
I don't know if is it the same of #285 :P

**Comment by celsoMartins** [comment]
Yes.. It is the same.. =)
