### ISSUE TITLE
Add information about the queue in the email for cancelation warning

### ISSUE THREAD

**Issue by celsoMartins** [agile-alliance-brazil/event_registrations#295]
If the event has an attendance queue, add a warning about it to the cancelation warning email.

Something like: Our event already has a queue. If we cancel your registration and you want to return, you will enter in this queue and you participation in event will not be guaranteed.

We need a better phrase, so I will be happy with your opinion. =)

**Comment by vieiragabriel** [comment]
Just trying to contribute....

"Hi there! We working with a queue list and need to warning you that your payment are NOT confirmed yet. If this confirmation not happens on next XX days the waiting people on that list are calling and you loose your place. So, if you change your mind and want to get back to attend of our event you go to this queue list too :)"

**Comment by hugocorbucci** [comment]
Suggestion:

Hello #{name},
#{event.name} is pretty full and we now have a waiting list. If you do not complete your registration in time and our automated system cancels it, you will have to submit a new registration which will add you to our waiting list.
