### ISSUE TITLE
The update for the logo information on event is not working

### ISSUE THREAD

**Issue by celsoMartins** [agile-alliance-brazil/event_registrations#305]

**Comment by hugocorbucci** [comment]
I can't reproduce this issue.
Are you sure:

1. The logo image is less than 1MB?
2. It is an image type? (PNG, GIF, JPEG, something whose mime type starts with image)

That's about it. Erica changed the logo of the 2016 edition in both prod and staging and had no problems so I  would guess something is working.

**Comment by celsoMartins** [comment]
The problem is in event form, as you can see on the attached video.

[logo_not_saving.zip](https://github.com/agile-alliance-brazil/event_registrations/files/255517/logo_not_saving.zip)

**Comment by hugocorbucci** [comment]
Ignore me. Wrong system.
