### ISSUE TITLE
Failed to start Vagrant machine

### ISSUE THREAD

**Issue by jonathanhds** [agile-alliance-brazil/event_registrations#312]
After cloning the repository and trying to starting up the Vagrant machine, I've received this error message:

```
$ vagrant up dev
Bringing machine 'dev' up with 'virtualbox' provider...
Bringing machine 'deploy' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* `private_key_path` file must exist: 
./event_registrations/certs/insecure_private_key
```

Any thoughts on resolving this issue?

**Comment by hugocorbucci** [comment]
Hey,
Sorry for the delay. You have an insecure (self-signed) vagrant private key
that should be in $HOME/.vagrant/ with that name. That's the one. If you
can copy it to that location it should work. We should just add a warning
about this.



Hugo Corbucci
Skype user: hugo.corbucci
Twitter: hugocorbucci

**Comment by jonathanhds** [comment]
It worked after setting up the vagrant private key, thanks @hugocorbucci!
