### ISSUE TITLE
Allow for registration payment before details are entered

### ISSUE THREAD

**Issue by hugocorbucci** [agile-alliance-brazil/event_registrations#32]
As a company with a fixed budget
I want to pay for a number of registrations upfront and fill in those details later
In order to secure cheaper values and spend my budget ideally

**Comment by celsoMartins** [comment]
Seems like registration groups solved this problem, right?

With groups, we can have any price we want for the event.

**Comment by celsoMartins** [comment]
We can solve it with a `paid group` concept, I think.

We can register a group setting the maximum size and an attribute to inform that it is a paid group.

The registrations in this group should be marked as paid automatically.

The logic that controls the size of the event and/or quota must count this group `paid group` now. So, if we have 50 positions left in the event and a paid group of 30 attendances is registered, we will have just 20 places left. The same for quotas. In this case, the group should have the information on quota or period in which it was registered.

The group should validate if has vacancy for the paid group. If it does not have vacancy, the group will not be created and the user will be warned.

Let me know if it is clear. =)
