### ISSUE TITLE
Minor translation issue

### ISSUE THREAD

**Issue by ceci** [agile-alliance-brazil/event_registrations#324]
**As a...** non-English speaker who speaks Portuguese
**I want...** the options on the _Nível de escolaridade_ field to be in Portuguese
**So that...** I put the correct information on that field

**Comment by ceci** [comment]
Although, really, I don't remember us ever using this info.

**Comment by celsoMartins** [comment]
So can we remove this information?

Please react until Thursday.

An information from First and Second Agile Floripa event: less than 10% of the attendees fill the non mandatory informations.

**Comment by ceci** [comment]
I'll leave this to @Hugo.corbuccu

**Comment by hugocorbucci** [comment]
I'd rather look historically at the Agile Brazil results to decide.
Having that information is an interesting data point for any diversity research we might want to do. Agile Floripa is much smaller and local so I wouldn't base our decisions on it. And translating shouldn't be the reason to stop this. ;)

**Comment by celsoMartins** [comment]
Never was, but a smaller and faster form was. I also had some UX advice on it. But ok. We can wait the Agile Brazil sample. Let me know when we have the right translation, please.
