### ISSUE TITLE
New list of job roles/positions

### ISSUE THREAD

**Issue by ceci** [agile-alliance-brazil/event_registrations#378]
**In order to...** provide better insights to both our Sponsors and the Program
**I want...** the list of roles to be a textfield in the backend with a list of suggestions in the frontend, with the values described in 
 ([this spreadsheet here](https://docs.google.com/spreadsheets/d/1OfN5pfqHyQVzCBAyAoVG7pfgPX2NaZJv1VWJoJJaH80/edit#gid=0))

**Comment by celsoMartins** [comment]
<img width="562" alt="Screen Shot 2021-06-06 at 8 02 32 PM" src="https://user-images.githubusercontent.com/214322/120942910-436cd500-c702-11eb-9db4-a3bf1b2f88d9.png">
