### ISSUE TITLE
Reorganize presentation of registration details

### ISSUE THREAD

**Issue by dtsato** [agile-alliance-brazil/event_registrations#43]
The data is being presented below the field name and with bullets.
Suggestion to remove bullets from the data, or include it in the same line as field name

Current presentation:
Registration details
. Name:
. Sarah Pimentel
. Registration Number:
. 16
. Status:
. Pending

Closes dtsato/agile_brazil#90 (moved to the right repo)

**Comment by celsoMartins** [comment]
This issue still relevant?
