### ISSUE TITLE
Go to a waiting list if an event is full

### ISSUE THREAD

**Issue by hugocorbucci** [agile-alliance-brazil/event_registrations#50]
As a late conference attendee
I want to add myself to a waiting list if I find out about an event after it's sold out
In order to get a chance to participate if anyone abandons or if the event increases its capacity

**Comment by celsoMartins** [comment]
- When a valid entrance exists in the waiting list, the new registrations should remain blocked. The new registrations will be only available with an empty waiting list;
- The user will fill a form identical to the normal registration one, but we will create a new status to map this new situation;
- When a user cancels his attendance or the field `attendance_limit` changes to a bigger capacity, the status of the next attendance in waiting list will be changed to `pending` and the user will receive an email
