### ISSUE TITLE
When registering using Oauth and submission system it informs the name is missing

### ISSUE THREAD

**Issue by giggio** [agile-alliance-brazil/event_registrations#57]
Just tried to register using oauth and the submission system and got this message:

    O serviço escolhido para autenticação não pôde nos informar seu nome. Por favor, preencha esta informação no serviço escolhido e tente autenticar-se novamente.

I have registered my name on the submissions system. There seems to be a bug.

**Comment by celsoMartins** [comment]
We need to review all auth system.
