### ISSUE TITLE
Limit registration per quantity not date

### ISSUE THREAD

**Issue by hugocorbucci** [agile-alliance-brazil/event_registrations#62]
As an Agile Brazil organizer,
I want to limit the registration types per number of registrations
So that I can predict the event's income from registrations

**Comment by celsoMartins** [comment]
https://github.com/agile-alliance-brazil/event_registrations/issues/79

**Comment by celsoMartins** [comment]
We developed a solution that we can use quotas and period, with period with priority over quotas. After validations from team, we can close this issue.
