### ISSUE TITLE
Upgrade ruby to 2.1

### ISSUE THREAD

**Issue by hugocorbucci** [agile-alliance-brazil/event_registrations#64]
Ruby 2.1 adds quite some performance improvement and the upgrade is quite painless from the application stand point.
The annoying part is just being able to upgrade the machines on the fly.
Either we change our deployment strategy to a phoenix server approach or we need rbenv.

There is a branch (ruby-2.1.5) with the code that works for ruby 2.1.5 but not the appropriate capistrano/deploy or puppet changes.

**Comment by celsoMartins** [comment]
Now to 2.2.3

I've tried it, but it broke snap ci.

**Comment by hugocorbucci** [comment]
I can fix snap.. it needs a config change. The rest worked?

**Comment by celsoMartins** [comment]
Locally worked perfectly.. When I commit to github, Snap crashed. I've tried some configurations, but unsuccessfully...

**Comment by hugocorbucci** [comment]
Did we get puppet to install ruby 2.2.3? Cause our deploys will fail otherwise

**Comment by celsoMartins** [comment]
I even know what puppet is.. =)

**Comment by celsoMartins** [comment]
I saw your tasks in issues, but I've not digged into it..

**Comment by hugocorbucci** [comment]
Puppet (https://puppetlabs.com/) is what automated the deployment machine
set up...
We have a folder (
https://github.com/agile-alliance-brazil/event_registrations/tree/master/puppet)
that contains the scripts that install everything we need to run the app in
our digital ocean machine.
Ruby would need to be upgraded in those machines...

Hugo Corbucci
Skype user: hugo.corbucci
Twitter: hugocorbucci

**Comment by celsoMartins** [comment]
Thanks for the explanation and for the folder localisation.

I'll take a look tonight.

We have two issues on it. #13 and #14
