### ISSUE TITLE
Register a group

### ISSUE THREAD

**Issue by celsoMartins** [agile-alliance-brazil/event_registrations#69]
As event manager, I should be able to register a group of attendees.

**Comment by hugocorbucci** [comment]
Groups should allow for:
* An administrator email who may or may not be attending the conference him/herself
* Groups will register over time and payment may be made at the end by the administrator or left as a future payment (government entities)
* Groups can only get the discount for their size applied after that many people are actually registered
* Once a group is confirmed, all attendees as well as the administrator have to receive a confirmation email. The admin should know how much it was and who was registered.
