### ISSUE TITLE
Change label button from Buy to Pay

### ISSUE THREAD

**Issue by celsoMartins** [agile-alliance-brazil/event_registrations#71]
Change the Bcash button's label at confirmation registration page.

**Comment by hugocorbucci** [comment]
Do we have a url for the new button?

**Comment by hugocorbucci** [comment]
Is this just in EN or in BR or both?

**Comment by celsoMartins** [comment]
In EN is even worse. If you check on attached images (that I just uploaded), you can see that in english we don't have translation for button label.

![bcash-button-en](https://cloud.githubusercontent.com/assets/214322/6885999/2dabcb62-d605-11e4-8611-6200663ad2ea.png)
![bcash-button-pt-br](https://cloud.githubusercontent.com/assets/214322/6886000/2dad0b58-d605-11e4-8c51-3c3bd03371b1.png)

**Comment by celsoMartins** [comment]
This screen comes after an attendance fill the registration form.

**Comment by celsoMartins** [comment]
Issue solved with the new gateway
