### ISSUE TITLE
Integration with AA to check members

### ISSUE THREAD

**Issue by celsoMartins** [agile-alliance-brazil/event_registrations#77]
We need to check if a attendance is an AA member due to member discounts.

**Comment by celsoMartins** [comment]
The AA integration was not resolved by AA. So we will use group and token to deal with AA members. Due this, I'm reducing this priority.

**Comment by hugocorbucci** [comment]
The API for AA is currently in development.
I'll update asap

Hugo Corbucci
Skype user: hugo.corbucci
Twitter: hugocorbucci

**Comment by celsoMartins** [comment]
Great!

**Comment by hugocorbucci** [comment]
API was improved. Not sure if the documentation is open so I sent it in an email to you.
